QT       += core gui
TARGET = targettest
TEMPLATE = app
HEADERS += \
./common/zy_code/zy_if.h\
./drivers/usb/ZY_CODE/Startup/lpc1700.h\
./drivers/usb/ZY_CODE/Startup/target.h\
./drivers/usb/ZY_CODE/zy_if/zy_if.h\
./drivers/usb/ZY_CODE/firmware.h\
./drivers/usb/cfg_file/Startup/LPC1700PinCfg.h\
./drivers/usb/cfg_file/Startup/vector_cfg.h\
./drivers/usb/cfg_file/zy_if/zy_if_cfg.h\
./drivers/usb/cfg_file/target_cfg.h\
./drivers/usb/usbDevLPC1700/isp1301.h\
./drivers/usb/usbDevLPC1700/usbDevCI.h\
./drivers/usb/usbDevLPC1700/usbDevConfig.h\
./drivers/usb/usbDevLPC1700/usbDevDMA.h\
./drivers/usb/usbDevLPC1700/usbDevDescriptor.h\
./drivers/usb/usbDevLPC1700/usbDevDriver.h\
./drivers/usb/usbDevLPC1700/usbDevHAL.h\
./drivers/usb/usbDevLPC1700/usbDevProtocol.h\
./drivers/usb/usbDevLPC1700/usbReg.h\
./drivers/usb/config.h\
./include/board/lpc1752/hardware_sets.h\
./include/board/lpc1752/irq_manage.h\
./include/board/test/test_hw.h\
./include/common/lcd_printf.h\
./include/common/utils.h\
./include/drivers/CTimeDef.h\
./include/drivers/delay.h\
./include/drivers/irq_timer.h\
./include/drivers/led.h\
./include/drivers/ops_w25qxx.h\
./include/drivers/timer_all.h\
./include/drivers/uart0.h\
./include/drivers/uart1.h\
./include/drivers/uart_all.h\
./include/drivers/w25q256.h\
./include/system/LPC17xx.h\
./include/system/lpc17xx_uart.h\
./include/system/system_LPC17xx.h\
./include/includeall.h\
./include/type.h
SOURCES += \
./board/lpc1752/hardware_sets.c\
./board/lpc1752/irq_manage.c\
./board/test/test_hw.c\
./common/printf/lcd_printf.c\
./common/system/core_cm3.c\
./common/system/system_LPC17xx.c\
./common/zy_code/zy_if.c\
./common/utils.c\
./drivers/delay/delay.c\
./drivers/led/led.c\
./drivers/serial/uart0.c\
./drivers/serial/uart1.c\
./drivers/serial/uart_all.c\
./drivers/spi/w25q256_ssp/ops_w25qxx.c\
./drivers/spi/w25q256_ssp/w25q256.c\
./drivers/timer/CTimeDef.c\
./drivers/timer/irq_timer.c\
./drivers/timer/timer_all.c\
./drivers/usb/ZY_CODE/Startup/LPC1700PinCfg.c\
./drivers/usb/ZY_CODE/Startup/target.c\
./drivers/usb/ZY_CODE/Startup/vector_table.c\
./drivers/usb/ZY_CODE/zy_if/zy_if.c\
./drivers/usb/cfg_file/Startup/rt_sys_c.c\
./drivers/usb/usbDevLPC1700/isp1301.c\
./drivers/usb/usbDevLPC1700/usbDevCI.c\
./drivers/usb/usbDevLPC1700/usbDevDMA.c\
./drivers/usb/usbDevLPC1700/usbDevDescriptor.c\
./drivers/usb/usbDevLPC1700/usbDevDriver.c\
./drivers/usb/usbDevLPC1700/usbDevHAL.c\
./drivers/usb/usbDevLPC1700/usbDevProtocol.c\
./src/main.c


INCLUDEPATH +=\
./Annotation\
./board\
./board/lpc1752\
./board/test\
./common\
./common/printf\
./common/system\
./common/zy_code\
./doc\
./drivers\
./drivers/delay\
./drivers/led\
./drivers/serial\
./drivers/spi\
./drivers/spi/w25q256_ssp\
./drivers/timer\
./drivers/usb\
./drivers/usb/ZY_CODE\
./drivers/usb/ZY_CODE/Startup\
./drivers/usb/ZY_CODE/zy_if\
./drivers/usb/cfg_file\
./drivers/usb/cfg_file/Startup\
./drivers/usb/cfg_file/zy_if\
./drivers/usb/usbDevLPC1700\
./include\
./include/board\
./include/board/lpc1752\
./include/board/test\
./include/common\
./include/drivers\
./include/system\
./output\
./prj\
./sourceinsight\
./src
